import { addIcons } from 'oh-vue-icons'
import {
    FaUser,
    FaBlog,
    FaBookOpen,
    FaDoorClosed,
    FaDoorOpen,
    BiPersonWorkspace,
    FcOpenedFolder,
    FcFolder,
    IoClose,
    BiGift,
    MdWavinghandOutlined,
    MdWavinghand,
    ViFileTypeJs,
    ViFileTypeGo,
    ViFileTypeCpp2,
    ViFileTypeC,
    ViFileTypePhp3,
    ViFileTypeJar,
    ViFileTypeJulia,
    ViFileTypeMatlab,
    ViFileTypePython,
    ViFileTypeBinary,
    GiHamburgerMenu,
} from 'oh-vue-icons/icons'

export function importIcons() {
    addIcons(
        FaUser,
        FaBlog,
        FaBookOpen,
        FaDoorClosed,
        FaDoorOpen,
        BiPersonWorkspace,
        FcFolder,
        FcOpenedFolder,
        IoClose,
        BiGift,
        MdWavinghandOutlined,
        MdWavinghand,
        ViFileTypeJs,
        ViFileTypeGo,
        ViFileTypeCpp2,
        ViFileTypeC,
        ViFileTypePhp3,
        ViFileTypeJar,
        ViFileTypeJulia,
        ViFileTypeMatlab,
        ViFileTypePython,
        ViFileTypeBinary,
        GiHamburgerMenu,
    )
}