name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Build Backend
        run: |
          cd backend
          sed -i -e "s|http://localhost:5173|https://giftmugweni.com,http://localhost:5173,https://*.masvingo.org|" main.go
          go build -o bin/

      - name: Push to DigitalOcean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{secrets.DROPLET_USERNAME}}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "backend/bin"
          target: "/var/www/personal-site"

      - name: Restart Backend Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{secrets.DROPLET_USERNAME}}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: sudo systemctl restart goweb

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Building Front End
        run: |
          cd frontend
          sed -e 's|{{GIPHY_API_KEY}}|$API_KEY|' -e 's|{{PRIV_API_URL}}|https://api.giftmugweni.com|' -e 's|{{BASE_URL}}|https://giftmugweni.com|' .env > .env.production
          npm install
          npm run build
          git clone https://$PAT@github.com/Stelele/personal-site-build.git out
          rm -r out/*
          cp -R dist/* out/
          cd out
          cp index.html 404.html
          git config --global user.email "giftmugweni@gmail.com"
          git config --global user.name "stelele"
          git add .
          git commit -m "Deploy build files"
          git push origin $DEPLOY_BRANCH
        env:
          API_KEY: ${{ secrets.GIPHY_API_KEY }}
          DEPLOY_BRANCH: main
          PAT: ${{ secrets.PAT }}

