name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Setup Env Variables
        run: sed 's/{{GIPHY_API_KEY}}/$GIPHY_API_KEY/' .env > .env.production
        env:
          GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Deploy to separate repository
        env:
          DEPLOY_BRANCH: main
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://$PAT@github.com/Stelele/personal-site-build.git out
          rm -r out/*
          cp -R dist/* out/
          cd out
          cp index.html 404.html
          git config --global user.email "giftmugweni@gmail.com"
          git config --global user.name "stelele"
          git add .
          git commit -m "Deploy build files"
          git push origin $DEPLOY_BRANCH
